### PR TITLE
0.x

### PR DESCRIPTION
**Pull request by jsenko**
The `1.3.x-snapshot` tag is not yet available. hi @riprasad any news on that?

Do not merge, this PR will be pushed as a new branch.

### CODE REVIEW

**Comment by famartinrh** [comment]
two questions:
why not updating the `install.yaml` file?, you are only updating the `install-dev.yaml` file.
wdyt about replacing the `{OPERATOR_IMAGE}` placeholder with the appropiate container image? given this is an historic branch, it will help to ease the installation when someone come back to this branch in the future. I even think we could do this change also in master...

**Comment by jsenko** [comment]
> two questions:
> why not updating the `install.yaml` file?, you are only updating the `install-dev.yaml` file.
> wdyt about replacing the `{OPERATOR_IMAGE}` placeholder in the `deploy/operator.yaml` file with the appropiate container image? given this is an historic branch, it will help to ease the installation when someone come back to this branch in the future. I even think we could do this change also in master...

I've responded in https://github.com/Apicurio/apicurio-registry-operator/pull/110#issuecomment-758593189 :)

**Comment by riprasad** [comment]
@jsenko The changes are done. The PR needs to be reviewed and merged. I will update you once the PR is merged

**Comment by riprasad** [comment]
> The `1.3.x-snapshot` tag is not yet available. hi @riprasad any news on that?

@jsenko changes are now merged to master.

**Comment by EricWittmann** [comment]
Changes to the workflows are merged I think, but I'll need to manually push 1.3.x-snapshot and 1.2.x-snapshot images to quay and docker hub.  Or I guess we could just make a trivial change/commit on each of those branches to trigger the build from CI.

**Comment by EricWittmann** [comment]
I'm on it. :)

**Comment by EricWittmann** [comment]
OK I've triggered CI builds for both 1.2.x and 1.3.x that should result in the new -snapshot docker images to be pushed.  As soon as those CI builds complete, the images should be ready to go.

**Pull request closed without merging**
