### PR TITLE
feat: Support SSL in the deployed registry

### PR DESCRIPTION
**Pull request by ajborley**
... via a new `spec.configuration.security.tls` field in the CR,
allowing users to supply a certificate and key to set up SSL on port
8443 in the registry deployment and service.

Contributes to: #70

Signed-off-by: Andrew Borley <BORLEY@uk.ibm.com>

### CODE REVIEW

**Comment by jsenko** [comment]
Hi, thank you or the PR, I'm testing it now

**Comment by ajborley** [comment]
@jsenko - any feedback for this PR? Did you have any success in your testing? Thanks :)

**Comment by ajborley** [comment]
@jsenko - have you had a chance to try this PR out? Thanks!

**Comment by FrancisMcNameeIBM** [comment]
Do you guys think this HTTPS support enhancement will be merged soon? I've got a forked version of the Apicurio operator where we added HTTPS support too, but it would be good to be able to use the latest version of the operator and not use a fork.

**Comment by ajborley** [comment]
@jsenko @EricWittmann - anything I can do to help get this tested/reviewed?

**Comment by jsenko** [comment]
I've been testing this and `JAVA_OPTIONS` is not being set for me. I'm going to see where the problem is. In addition, we need to add some examples and documentation.
I apologize for this taking so long. We've been busy with other issues and projects.

**Comment by jsenko** [comment]
This PR is stale, so I'm closing it. The HTTPS support has been implemented via different PRs.

**Pull request closed without merging**
