### PR TITLE
Add a network policy to the registry

### LINKED ISSUE #158: Add a NetworkPolicy resource to the controller.
It is generally good practice to use a NetworkPolicy resource to control the network traffic a given resource is exposed to. At the moment the apicurio-registry deployment has no NetworkPolicy defined. To fix this, I suggest adding a `CreateNetworkPolicy` method to `factory_kube.go` to define the resource and adding a corresponding control function. Let me know what you think.
Thanks

### PR DESCRIPTION
**Pull request by jhughes24816**
Resolves #158

Added a network policy to the that the operator manages:

- Currently exposes port 8080 for ingress.
- I suggest we use this PR to discuss what the form of the policy should be.

### CODE REVIEW

**Comment by jhughes24816** [comment]
@jsenko Could you please take at this PR (similar to the other one):
`There were failures detected in the following suites:
   multinamespace ./testsuite/olm/multinamespace
  singlenamespace ./testsuite/olm/singlenamespace`
These test suites seem to be failing on the `BeforeSuite` and they don't seem to be related to the code changes in the PR? Thank you!

**Comment by jhughes24816** [comment]
@jsenko Could you please give this a review? I would be interested to have your thoughts/suggestions :)

**Comment by jhughes24816** [comment]
@jsenko Can I get a review on this please?

**Review by jsenko — APPROVED** [review]
This looks good. Thank you.

**Pull request merged**
