### PR TITLE
docs: remove tp notice for sso

### PR DESCRIPTION
**Pull request by smccarthy-ie**
Remove Technology Preview notice for RH-SSO Operator (no longer applies, GA feature since RH-SSO v7.5)

### CODE REVIEW

**Comment by smccarthy-ie** [comment]
@EricWittmann @jsenko Can you review/merge this one? Thanks

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Not sure why the PR check is failing.  Will let @jsenko figure that out. :

**Comment by jsenko** [comment]
I'm re-running the tests, will investigate otherwise.

**Comment by smccarthy-ie** [comment]
@jsenko Checks are still failing. Looks like nothing to do with text-only doc PR. Seems to be Operator build couldn't initialize a Kubernetes cluster?

https://github.com/Apicurio/apicurio-registry-operator/runs/8021712551?check_suite_focus=true

**Pull request merged**
