### PR TITLE
Fix the issue #45 and  #43 to delete all CR resources

### PR DESCRIPTION
**Pull request by redhatHameed**
Signed-off-by: Abdul Hameed <ahameed@redhat.com>

### CODE REVIEW

**Comment by redhatHameed** [comment]
@jsenko Could you please review this PR: 

Steps:

``` ./build.sh mkdeploy -r  <registry>-n <namespace>```

once operator and operand successfully deployed, delete the CR 

```oc delete -f deploy/crds/apicur.io_apicurioregistries_cr.yaml```

**Comment by jsenko** [comment]
Hi @redhatHameed , sorry for late response.

I'm getting the following error(s) on minikube:
```
{"level":"info","ts":1599134962.5546389,"logger":"controller_apicurioregistry","msg":"Reconciler executing.","namespace":"default","app":"example-apicurioregistry"}

{"level":"info","ts":1599134962.6546168,"logger":"controller_apicurioregistry","msg":"No Custom Resource found named %s. Checking for dependent objects to delete.example-apicurioregistry","namespace":"default","app":"example-apicurioregistry"}

{"level":"dpanic","ts":1599134966.8553069,"logger":"controller_apicurioregistry","msg":"odd number of arguments passed as key-value pairs for logging","namespace":"default","app":"example-apicurioregistry","ignored key":"no matches for kind \"DeploymentConfig\" in version \"apps.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.handleFields\n\t/home/jsenko/projects/3scale/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106\ngithub.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jsenko/projects/3scale/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:129\ngithub.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.getDeployedResources\n\tapicurio-registry-operator/pkg/controller/apicurioregistry/control_loop.go:270\ngithub.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.(*ApicurioRegistryReconciler).Reconcile\n\tapicurio-registry-operator/pkg/controller/apicurioregistry/control_loop.go:61\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

{"level":"error","ts":1599134966.8550675,"logger":"controller_apicurioregistry","msg":"Failed to list deployed objects. ","namespace":"default","app":"example-apicurioregistry","error":"no matches for kind \"DeploymentConfig\" in version \"apps.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jsenko/projects/3scale/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.getDeployedResources\n\tapicurio-registry-operator/pkg/controller/apicurioregistry/control_loop.go:270\ngithub.com/Apicurio/apicurio-registry-operator/pkg/controller/apicurioregistry.(*ApicurioRegistryReconciler).Reconcile\n\tapicurio-registry-operator/pkg/controller/apicurioregistry/control_loop.go:61\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

{"level":"error","ts":1599134967.0546122,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"apicurioregistry-controller","request":"default/example-apicurioregistry","error":"no matches for kind \"DeploymentConfig\" in version \"apps.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jsenko/projects/3scale/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/jsenko/projects/3scale/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/jsenko/projects/3scale/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

{"level":"info","ts":1599134968.0551662,"logger":"controller_apicurioregistry","msg":"Reconciler executing.","namespace":"default","app":"example-apicurioregistry"}

{"level":"info","ts":1599134968.0552635,"logger":"controller_apicurioregistry","msg":"No Custom Resource found named %s. Checking for dependent objects to delete.example-apicurioregistry","namespace":"default","app":"example-apicurioregistry"}
```
Any idea what could be the problem? The operator supports both k8s and OpenShift, and `DeploymentConfig` is mentioned, which is only used when deployed on OpenShift. I'm going to investigate.

**Comment by jsenko** [comment]
Another approach could be to have the cleanup logic inside of the context (and/or let the control functions delete the resources), which would be executed when the context is removed. This would allow additional cleanup functionality to be executed, in addition to deleting the resources.

**Comment by redhatHameed** [comment]
@jsenko are you still facing the error? I done testing using openshift environment.it works with me without any error.

**Comment by jsenko** [comment]
I'm closing this pull request in favor of #76 which uses a somewhat different approach. Thank you for all contributions!

**Pull request closed without merging**
