### PR TITLE
Updated operator-sdk version to 1.7.0 and made necessary changes.

### PR DESCRIPTION
**Pull request by jhughes24816**
Updated operator-sdk version.
This provides access to features release in the past year.

### CODE REVIEW

**Comment by jhughes24816** [comment]
@jsenko Could you run the workflow against this and give it a review please? Thanks

**Comment by jsenko** [comment]
Running the workflow now, the changes are LGTM

**Review by ajborley — APPROVED** [review]
LGTM (from a non-maintainer)

**Comment by jsenko** [comment]
Thanks!

**Comment by jhughes24816** [comment]
With the introduction of the scorecard for testing is it worth adding tests to the operator itself rather than relying on tests run in the workflow on a PR? 

(Is that what [these tests](https://github.com/Apicurio/apicurio-registry-k8s-tests-e2e) are used for?)

**Comment by jsenko** [comment]
Those are integration tests for the Operator, yes. We are currently working on improving them and rewriting them to Java (so they can be better maintained by our new QE team, led by @obabec). The current plan is to move them into this repo. Let's wait until we figure it out.

**Pull request merged**
